### ISSUE TITLE
deploy.prototxt

### ISSUE THREAD

**Issue by kaishijeng** [DeepScale/SqueezeNet#1]
Do you have a plan to release deploy.prototxt?
I plan to run classify.py from Caffe to test squeezenet performance for images I have and compare it with alexnet

.

**Comment by forresti** [comment]
I would accept a Pull Request of deploy.prototxt if you'd like to create one. It's pretty straightforward...
1. Replace the two data layers with `input_shape{dim: ...}`
2. Change `SoftmaxWithProb` to `Softmax`
3. Remove the `accuracy` and `accuracy_top5` layers

With these three changes, I think you'll have a file that matches the syntax of the bvlc_alexnet and bvlc_googlenet deploy.prototxt files.

**Comment by kaishijeng** [comment]
Thanks for the instruction. Let me try first and if it works properly, I
can submit it for a pull request

**Comment by kaishijeng** [comment]
I create a deploy.prototxt and it runs OK with Caffe. I also notice someone already creates a PR for deploy.prototxt which is the same as my version. I will not submit a PR and close this issue now
