### ISSUE TITLE
Why v1.1 does not have deploy.prototxt

### ISSUE THREAD

**Issue by changyun79** [DeepScale/SqueezeNet#12]
Hello, 
I am wondering why v1.1 does not have deploy.prototxt. Missed commit? Thank you.

**Comment by forresti** [comment]
We can add that. Thanks to @terrychenism for creating this on SqueezeNet v1.0.

Nobody on our team uses the deploy.prototxt interface very often... we mostly load custom training/testing sets into LMDBs to avoid being bottlenecked by I/O.

**Comment by changyun79** [comment]
Thanks for the quick response. I appreciate if it can be added in.

**Comment by besirkurtulmus** [comment]
I'd also appreciate if you could add deploy.txt too.

**Comment by austingg** [comment]
@besirkurtulmus it's quite easy to make deploy.prototxt with reference train_val.prototxt. You can just modified the input and output layers and there are some reference in Caffe/models directory.

**Comment by psyhtest** [comment]
@forresti 

I thought one needs `deploy.prototxt` to measure the execution time using `caffe time`? I appreciate your research is mostly about achieving the same accuracy but what about performance?

**Comment by forresti** [comment]
I often run `caffe time` on `train_val.prototxt` files... it works great. :)

**Comment by psyhtest** [comment]
forresti
Thanks! Do you know which batch size gets picked up for benchmarking - from the `TRAIN` or `TEST` specification? Is it deterministic?

**Comment by forresti** [comment]
I think `train`. But, `caffe time` will print the dimensions of all layers
including the batch size.

**Comment by AliaMYH** [comment]
What exactly is the difference between the train_val and the deploy prototxt ? What are their different purposes?

**Comment by amroamroamro** [comment]
@forresti
there's now three PRs to add `deploy.txt` for v1.1: #20, #21, #43
