### ISSUE TITLE
why the conv10 in SqueezeNet1.0 has a pad of 1?

### ISSUE THREAD

**Issue by cc946079647** [DeepScale/SqueezeNet#14]
conv10 is a layer which has only 1*1 conv filters,could anyone please tell me why the pad is set to 1?thanks

**Comment by forresti** [comment]
We generated the SqueezeNet programmatically (not writing prototxt by hand), so benign quirks like this sometimes creep in. 

If you try disabling the conv10 padding, I would anticipate that it will work ok. Feel free to give it a try and let us know what happens!
