### ISSUE TITLE
build my own sqeezenet

### ISSUE THREAD

**Issue by zhaishengfu** [DeepScale/SqueezeNet#22]
@forresti  I want to use your idea to sqeeze my own big network, but i have no idea how to implement it. Can you give me some ideas to sqeeze any big model?? Can I use the original model to finetune the sqeezed model??

**Comment by forresti** [comment]
SqueezeNet isn't a big network that's squeezed. SqueezeNet is a small network that we trained from scratch.

**Comment by sunjunlishi** [comment]
want to use your idea to sqeeze my own  network，could it works?
