### ISSUE TITLE
Padding in conv-10 layer 

### ISSUE THREAD

**Issue by AlexandreBriot** [DeepScale/SqueezeNet#27]
Hello 
I wonder why we need to use pad=1 in conv-10 layer.
What is the goal to use padding with a 1x1 kernel ?
Thanks in advance for your help.
Alex

layer {
  name: "conv10"
  type: "Convolution"
  bottom: "fire9/concat"
  top: "conv10"
  convolution_param {
    num_output: 1000
    pad: 1
    kernel_size: 1
  }
}

**Comment by chibai** [comment]
@AlexandreBriot
check the closed issue 14
you can close the issue i guess
