### ISSUE TITLE
SqueezeNet spped slower than Alexnet

### ISSUE THREAD

**Issue by ChristineRYY** [DeepScale/SqueezeNet#29]
@macd @forresti @antingshen @samster25 @terrychenism 
Hi, I use command"
caffe.exe time --model=SqueezeNet_v1.1_deploy.prototxt -gpu 0 -iterations 100
" to test the time.
AlexNet:11ms, SqueezeNet:30ms.
even use cudnn v4, the time of SqueezeNet is still twice or even three times than AlexNet.
Do you have any advice?

**Comment by chibai** [comment]
The contribution of squeeze net is the model size not the computational complexity~~
Actually, computational complexity of Alexnet and SqueezeNet are similar~

**Comment by maydaygmail** [comment]
Interesting issue! @forresti would you please explain why  much less parameters but use much more time?

**Comment by austingg** [comment]
@maydaygmail  the most majority of model parameter is in FC layers.  and the most computation cost at conv layers. Squeezenet use more Conv layers, it's much deeper than alexnet

**Comment by maydaygmail** [comment]
Thanks @austingg. I think there is a implementation problem. In fire module, expand layer has 2 different convolution, and the 2 different convolution are calculating serially not parallel
