### ISSUE TITLE
conv10 layer has pad 1

### ISSUE THREAD

**Issue by psyhtest** [DeepScale/SqueezeNet#32]
As noticed by @milakov, it's quite surprising to see the following 1x1 convolutional layer having the padding of 1:.
```
layer {
  name: "conv10"
  type: "Convolution"
  bottom: "fire9/concat"
  top: "conv10"
  convolution_param {
    num_output: 1000
    pad: 1
    kernel_size: 1
  }
}
```
Any comments?

**Comment by forresti** [comment]
Duplicate issue. See #14

**Comment by psyhtest** [comment]
@forresti Thanks! (I really should have guessed this as a compiler person used to generating correct if redundant code :))

**Comment by forresti** [comment]
Haha yup, that's exactly what happened. :)
