### ISSUE TITLE
v1.1 dimensions mismatch in the first layers

### ISSUE THREAD

**Issue by gudovskiy** [DeepScale/SqueezeNet#33]
Hi, seems that original v1.0 had nice dimension relationships:
227 -> (227-7)/2+1=111 -> (111-3)/2+1=55 etc.
But in v1.1 we start to get:
227 -> (227-3)/2+1=113 -> (113-3)/2+1=56 etc.

To get output of conv1 to be 111, input image should be decreased to 223x223. Not sure how exactly Caffe handles this, but something mismatch in v1.1. Any idea?

**Comment by forresti** [comment]
You can look in the conv_layer.cpp
code in Caffe for the details of the rounding scheme. But, yes, there is a rounding scheme, and it all works nicely.
