### ISSUE TITLE
Train SqueezeNet from scratch ?

### ISSUE THREAD

**Issue by phongnhhn92** [DeepScale/SqueezeNet#37]
Hello guys, I want to train SqueezeNet  from scratch with my own data instead of using ImageNet dataset. I would like to ask is that possible or not. I am new to Caffe, I already know Tensorflow but seems like there is no SqueezeNet Tensorflow version support.

**Comment by mrgloom** [comment]
Try this:
https://github.com/mrgloom/kaggle-dogs-vs-cats-solution/tree/master/learning_from_scratch/SqeezeNet_v1.1

**Comment by varunlakshmanan** [comment]
@mrgloom I have the same question, but specifically for building for iOS. Are there any other resources you know of that could help with this?

**Comment by mrgloom** [comment]
Not sure of caffe2 is compatible with caffe models, in my repo you can find all .prototxt that needed to train model. Also I was using caffe+DIGITS to train model, DIGITS simplifies DB creation, if we are talking about classification.
