### ISSUE TITLE
Number of anchors reducing mAP 

### ISSUE THREAD

**Issue by soyebn** [DeepScale/SqueezeNet#40]
Any intuition why does increasing number of anchors from 9 to 16, decreases mAP  by 10%? I was expecting if it does not increase mAP at least it should have kept same. Is it due to replacing FC with conv layer in your SqueezeDet vs. YOLO?

**Comment by sunnyxiaohu** [comment]
How do you set the layer of learning rate and initialization mode ? weight_filler {
      type: "xavier"
    }
    bias_filler {
      type: "constant"
      value: 0
    }

param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }

??
How about the freeze_layers ?

**Comment by forresti** [comment]
This repo is SqueezeNet Are you looking for SqueezeDet?
https://github.com/BichenWuUCB/squeezeDet
