### ISSUE TITLE
model convert

### ISSUE THREAD

**Issue by wm901115nwpu** [DeepScale/SqueezeNet#44]
I use the tensorflow, how to convert the .caffemodel to .pkl. Thank you!!!

**Comment by forresti** [comment]
Based on a quick google search, it looks like there are now several SqueezeNet implementations using TensorFlow.

https://github.com/vonclites/squeezenet
https://github.com/avoroshilov/tf-squeezenet
https://github.com/Dawars/SqueezeNet-tf
