### ISSUE TITLE
Wrong Numbers?

### ISSUE THREAD

**Issue by tmatas** [DeepScale/SqueezeNet#6]
Hello,
I'm trying to use this model, but the number in the various strata looks weird.
Shouldn't the input be 3X224x224, as in the paper, instead of 3X227x227?
And what does it mean that the first dimension is 10?

btw, awesome work.

**Comment by forresti** [comment]
Thanks for your kind words.

Good point about 224 vs 227. This is a typo in the paper. But, we have
found that the accuracy of our CNNs aren't too sensitive to 224 vs 227.
Substantially larger input image sizes might lead to higher accuracy.

In deploy.prototxt, 10 is the batch size.
